# Generated by Django 6.0.1 on 2026-01-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_dates",
                        to="tours.tourpackage",
                    ),
                ),
            ],
        ),
    ]
