# Generated by Django 6.0.1 on 2026-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tourdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="destinations/"),
        ),
    ]
