# Generated by Django 6.0.1 on 2026-01-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_destination_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Short title like 'Sunset in Bali'",
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/public/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Public Gallery Image",
                "verbose_name_plural": "Public Gallery Images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
