# Generated by Django 6.0.1 on 2026-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "customer_title",
                    models.CharField(
                        blank=True, help_text="e.g. Traveler from USA", max_length=100
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="reviews/"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("comment", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
