# Generated by Django 6.0.1 on 2026-01-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4, WebM, or OGG video files",
                null=True,
                upload_to="gallery/videos/",
            ),
        ),
    ]
