# Generated by Django 6.0.1 on 2026-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_galleryimage_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image file",
                null=True,
                upload_to="gallery/public/",
            ),
        ),
    ]
